title: فروشگاه مام‌لِم
description: محصولات آرایشی و بهداشتی با قیمت عمده
baseurl: ""
url: "https://jalaluddin-yaqubi.github.io"
lang: fa
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  products:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: products
    values:
      layout: product
